# Generated by Django 5.1.4 on 2025-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='members_split',
            field=models.JSONField(default=dict),
        ),
    ]
