# Generated by Django 5.1.4 on 2025-01-11 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_members_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='expense',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.expense'),
        ),
        migrations.AddField(
            model_name='settlement',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.group'),
        ),
    ]
