# Generated by Django 5.1.4 on 2025-01-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_settlement_expense_settlement_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
